#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║              Shadow Quick Demo                             ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 Available Commands:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Basic Scan"
echo "   ./shadow scan example.com"
echo ""
echo "2. Quick Scan (faster)"
echo "   ./shadow scan example.com --profile quick"
echo ""
echo "3. Deep Scan (comprehensive)"
echo "   ./shadow scan example.com --profile deep"
echo ""
echo "4. Scan with AI Analysis (requires API key)"
echo "   ./shadow scan example.com --ai-analysis"
echo ""
echo "5. Subdomain Discovery"
echo "   ./shadow subdomain example.com"
echo ""
echo "6. Port Scanning"
echo "   ./shadow portscan example.com"
echo ""
echo "7. SSL/TLS Check"
echo "   ./shadow ssl example.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Tips:"
echo "   • Always get permission before scanning!"
echo "   • Use --profile quick for fast checks"
echo "   • Add --ai-analysis for intelligent insights"
echo "   • Results saved in scan_results/ directory"
echo ""
echo "⚙️  Configuration:"
echo "   Config file: ~/.shadow/config.yaml"
echo "   API key: Set ANTHROPIC_API_KEY environment variable"
echo ""
echo "📚 Documentation:"
echo "   • README.md - Overview"
echo "   • GETTING_STARTED.md - Tutorial"
echo "   • WHY_SHADOW.md - Why use Shadow"
echo "   • ARCHITECTURE.md - Technical details"
echo ""
