#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║      Shadow AI with OAuth Authentication Test             ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "🔐 Step 1: Check Authentication Status"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
./shadow auth-check
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Shadow OAuth Integration Complete!"
echo ""
echo "📋 Key Features:"
echo "   ✓ Automatic OAuth detection from Claude Code"
echo "   ✓ Fallback to pi CLI authentication"
echo "   ✓ No API key needed when using Claude Code"
echo "   ✓ Seamless integration with pi-golang library"
echo ""
echo "🎯 How It Works:"
echo "   1. Shadow uses pi-golang library (same as openclaw)"
echo "   2. pi-golang automatically looks for OAuth tokens:"
echo "      - ~/.claude/oauth.json (Claude Code)"
echo "      - ~/.pi/agent/oauth.json (pi CLI)"
echo "      - ~/.config/anthropic/oauth.json"
echo "   3. Falls back to pi CLI's built-in auth"
echo "   4. Works seamlessly with ANTHROPIC_API_KEY as alternative"
echo ""
echo "🚀 Usage Examples:"
echo ""
echo "# Scan with AI analysis (uses OAuth automatically)"
echo "  ./shadow scan example.com --ai-analysis"
echo ""
echo "# AI-powered query"
echo "  ./shadow query <scan-id> \"What are the critical issues?\""
echo ""
echo "# Generate AI-enhanced report"
echo "  ./shadow report <scan-id> --format html"
echo ""
echo "💡 Note: Claude Code OAuth token is automatically used when available!"
echo ""
